### ISSUE TITLE
UI Scaling breaks at large resolutions

### ISSUE THREAD

**Issue by ponyfan88** [XanderMooney/Scoundrills#15]
"on large resolutions such as 4K monitors, some elements can cover the majority of the screen when fullscreened. This needs to be fixed sooner rather than later." -@XanderMooney

i moved this over here as this is an issue with scoundrills. ive made a commit for this ([c92633b](https://github.com/XanderMooney/Scoundrills/commit/c92633b54110eb9304fcee6031dec46b66bb1edc)). please test this further @XanderMooney

**Comment by XanderMooney** [comment]
This seems to have been fixed when the release mode bug for UI was fixed 👍
