### ISSUE TITLE
Pause Menu

### ISSUE THREAD

**Issue by XanderMooney** [XanderMooney/Scoundrills#4]
Prerequisites:
- Freezes the game -- we already have a "timescale" variable in the time class, but its not actually applied to anything ever.
- Keybind changing -- the base for this is already done within inputManager, we now just have to build it and fix any oversights with the system.
- Sliders -- we are going to need sliders for options like audio, etc.
- Resolution changing

Im sure there is more not included on this list.

**Comment by ponyfan88** [comment]
could be done if we add a "game speed" variable into jauntlet::time or something like that

**Comment by XanderMooney** [comment]
As stated above, we already have a timeScale variable for this purpose

**Comment by XanderMooney** [comment]
Successfully added and integrated as of this week.
