### ISSUE TITLE
Outlying path tracing bugs

### ISSUE THREAD

**Issue by XanderMooney** [XanderMooney/Scoundrills#6]
- the arrow at the end of the path points towards the proposed destination and not the real destination (important for if we modify the destination)
- the path starts on-top of the player
- The path still renders even if the path isn't reachable

**Comment by XanderMooney** [comment]
The path nolonger renders if the path isn't reachable via [8802876](https://github.com/XanderMooney/Scoundrills/commit/88028760793bcd72b9c03c9f215cb80a97b05de5)

**Comment by ponyfan88** [comment]
@XanderMooney is this still an issue? i remember you fixing several pathfinding errors in front of me.

**Comment by XanderMooney** [comment]
Only the third issue bulleted still remains
