### ISSUE TITLE
Scene loading

### ISSUE THREAD

**Issue by XanderMooney** [XanderMooney/Scoundrills#7]
We need to be able to unload and load specific scenes based on the state of the game. For this a scene manager of some sort is pretty much required

Requirements:
- Loading and unloading scenes
- Choosing some data to keep loaded
- Loading save data for specific scenes

**Comment by ponyfan88** [comment]
very vague, is a scene a datatype?

**Comment by XanderMooney** [comment]
Very vague because structure is undefined as of now.

We very clearly need some sort of structure for Scenes, however a class doesn't make much sense as you'd most certainly need to make a derived class for every scene, which isn't very good for what we need.

May be smart to inspect how other engines handle scenes and go from there

**Comment by XanderMooney** [comment]
This is finished within the bounds of Scoundrills. Why not Jauntlet? This is because we don't have an visual interface for Jauntlet, and I believe once we do we will want to be able to save and integrate data in a specific way that is inaccessible to us currently, such as keeping object positions stored in a file that would then be loaded once a scene is loaded; completely different from the system we use now.
